Dev
zadziarnouksi-taras/WorkoutLog pull request #4
Opened 2021-01-23 18:11 UTC by zadziarnouksi-taras

2021-01-26 11:23 UTC, RomanKashenok requested changes

2021-01-26 11:23 UTC, RomanKashenok commented on src/main/java/by/zadziarnouski/workoutlog/configuration/ConfigurationCloudinary.java
> +        return cloud;
such kind of properties better to store in repository variables (if ci/cd flow implemented) or in .properties file

2021-01-26 11:23 UTC, RomanKashenok commented on src/main/java/by/zadziarnouski/workoutlog/configuration/DatabaseFillingConfig.java
> +public class DatabaseFillingConfig {
All this data better to store in .sql file and execute it on application start

2021-01-26 11:23 UTC, RomanKashenok commented on src/main/java/by/zadziarnouski/workoutlog/configuration/WebSecurityConfiguration.java
> +                .anyRequest().permitAll()
why do you need row 44 if in 45 you permitting everyone to access your application?

2021-01-26 11:23 UTC, RomanKashenok commented on src/main/java/by/zadziarnouski/workoutlog/controller/ExerciseEditorController.java
> +@RequestMapping(path = "/exercise-editor")
try not to use separators like '-' in url

2021-01-26 11:23 UTC, RomanKashenok commented on src/main/java/by/zadziarnouski/workoutlog/controller/ExerciseEditorController.java
> +    @PostMapping("/create-update")
remove '-' from url

2021-01-26 11:23 UTC, RomanKashenok commented on src/main/java/by/zadziarnouski/workoutlog/controller/MeasurementLogController.java
> +@RequestMapping(path = "/measurement-log")
remove '-'

2021-01-26 11:23 UTC, RomanKashenok commented on src/main/java/by/zadziarnouski/workoutlog/controller/MenuController.java
> +    @RequestMapping(method = {RequestMethod.GET, RequestMethod.POST})
remove POST mapping

2021-01-26 11:23 UTC, RomanKashenok commented on src/main/java/by/zadziarnouski/workoutlog/controller/PersonalProfileController.java
> +    private UserDetails getPrincipal() {
Move this method to util class and make it return User. Make this new method static

2021-01-26 11:23 UTC, RomanKashenok commented on src/main/java/by/zadziarnouski/workoutlog/controller/WorkoutConstructorController.java
> +@RequestMapping(path = "/workout-constructor")
remove '-'

2021-01-26 11:23 UTC, RomanKashenok commented on src/main/java/by/zadziarnouski/workoutlog/controller/WorkoutConstructorController.java
> +    @PostMapping("/add-or-update-exercise-in-workout")
name more appropriate please ('store' for example or just 'save')

2021-02-09 06:08 UTC, closed without merging

2021-02-09 06:13 UTC, aimiebell commented on src/main/java/by/zadziarnouski/workoutlog/configuration/CloudinaryConfiguration.java
> +    public Cloudinary ConnectionToCloudinary() {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:13 UTC, aimiebell commented on src/main/java/by/zadziarnouski/workoutlog/controller/PersonalProfileController.java
> +    public String UpdateProfile(@ModelAttribute UserDTO userDTO, HttpSession session) {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:13 UTC, aimiebell commented on src/main/java/by/zadziarnouski/workoutlog/controller/WorkoutConstructorController.java
> +    public String StartTraining(HttpSession session, Model model) {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.